#!/bin/bash

echo
echo
echo 'Ensure that you have pi-listener*_latest.deb in the same directory. Ether run build or download from Github project.'
echo
echo

sudo dpkg -i pi-listener_latest.deb
sudo dpkg -i pi-listener-config_latest.deb

